version: '3.8'

services:
    nginx:
        container_name: nginx
        image: nginx:alpine
        ports:
            - "8080:80"
        depends_on:
            - app
            - db
        volumes:
            - ./storage:/var/www/storage
            - ./public:/var/www/public
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - app-network

    db:
        image: mysql
        container_name: mysql
        ports:
            - "3307:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: cost_estimate_prod_3
            MYSQL_ROOT_PASSWORD: password
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "3400:80"
        depends_on:
            - db
        networks:
            - app-network

    app:
        build:
            context: .
        ports:
            - "9000:9000"  # PHP-FPM port
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - app-network

    soketi:
        image: quay.io/soketi/soketi:latest-16-alpine
        container_name: soketi
        ports:
            - "6001:6001"
            - "9601:9601"
        environment:
            SOKETI_DEFAULT_APP_ID: "cost_estimate"
            SOKETI_DEFAULT_APP_KEY: "cost-estimate-key"
            SOKETI_DEFAULT_APP_SECRET: "cost-estimate-secret"
            SOKETI_DEFAULT_APP_MAX_CONNS: "100"
        networks:
            - app-network

    collab:
        image: node:20-alpine
        container_name: collab-ws
        working_dir: /app
        command: sh -c "npm install && npm start"
        ports:
            - "1234:1234"
        volumes:
            - ./ws-server:/app
        networks:
            - app-network

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

