version: '3.8'

services:
    nginx:
        container_name: nginx
        image: nginx:alpine
        ports:
            - "8080:80"
        depends_on:
            - app
            - db
        volumes:
            - ./public:/var/www/public
            - ./nginx/conf.d:/etc/nginx/conf.d
    db:
        image: mysql
        container_name: mysql
        ports:
            - "3307:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=cost_estimate_prod_3
            - MYSQL_ROOT_PASSWORD=password
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "3400:80"
        depends_on:
            - db
    app:
        build:
            context: .
        ports:
            - "9000:9000"  # PHP-FPM port
        volumes:
            - .:/var/www
        depends_on:
            - db

#version: '3.8'
#
#services:
#    nginx :
#        container_name: nginx
#        image: nginx:alpine
#        ports:
#            - "8080:80"
#        depends_on:
#            - app
#            - db
#        volumes:
#            -   ./src:/var/www
#            - ./nginx/conf.d/:/etc/nginx/conf.d
#    db:
#        image: mysql
#        container_name: mysql
#        ports:
#            - "3307:3306"
#        volumes:
#            -   ./mysql/data:var/lib/mysql
#        environment:
#            - MYSQL_DATABASE=cost_estimate_prod_3
#            - MYSQL_ROOT_PASSWORD=password
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: phpmyadmin
#        ports:
#            - "3400:80"
#        depends_on:
#            -   db
#    app:
#        build:
#            context: .
#        ports:
#            - "8000:8000"  # Expose the port 8000 for the app
#        volumes:
#            - .:/var/www
#        environment:
#            - APACHE_DOCUMENT_ROOT=/var/www/html/public
#            - APACHE_SERVER_NAME=localhost
#        depends_on:
#            - db
#

#    app:
#        build:
#            context: .
#        ports:
#            - "8000:8000"  # Expose the port 8000 for the app
#        volumes:
#            - .:/var/www
#        environment:
#            - APACHE_DOCUMENT_ROOT=/var/www/html/public
#            - APACHE_SERVER_NAME=localhost
#        depends_on:
#            - db
#
#    db:
#        image: mysql:8.4.3
#        environment:
#            MYSQL_ROOT_PASSWORD: P@ssw0rd        # Root password for MySQL
#            MYSQL_DATABASE: cost_estimate_prod_3  # Database name to create
#            MYSQL_USER: app_user                  # Non-root user for the app
#            MYSQL_PASSWORD: P@ssw0rd             # Password for the app user
#        ports:
#            - "3307:3306"  # Expose MySQL port 3306
#        volumes:
#            - db-data:/var/lib/mysql  # Persistent volume for MySQL data

#volumes:
#    db-data:
